# Generated by Django 5.2.8 on 2025-11-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_name",
                    models.CharField(
                        db_index=True,
                        help_text="Идентификатор меню (например: main_menu, footer_menu)",
                        max_length=50,
                        verbose_name="Имя меню",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Явный URL (например: /about/)",
                        max_length=200,
                        verbose_name="URL",
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        help_text="Имя URL из urls.py (например: about)",
                        max_length=100,
                        verbose_name="Named URL",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок сортировки (меньше = выше)",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="treemenu.menuitem",
                        verbose_name="Родительский пункт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ["order", "title"],
            },
        ),
    ]
