# Generated by Django 5.2.8 on 2025-12-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treemenu", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["menu_name", "order"], name="treemenu_me_menu_na_59b795_idx"
            ),
        ),
    ]
